import React from 'react';
import { Image, Linking, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link } from 'expo-router';
import { PrimaryButton } from '@/components/PrimaryButton';
import { Brand } from '@/constants/Colors';
import {
  BLOGS,
  CONTACT,
  HOW_IT_WORKS,
  PROJECTS,
  PURCHASE_NFT_URL,
  WEBSITE_URL,
} from '@/constants/Content';

export default function HomeScreen() {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      {/* Hero */}
      <View style={styles.hero}>
        <View style={styles.heroTextWrap}>
          <Text style={styles.heroTitle}>Invest in Carbon NFTs</Text>
          <Text style={styles.heroSubtitle}>
            Solutions for Environmental Impact and Investment gains for you.
          </Text>
          <PrimaryButton title="Purchase Carbon NFTs" href={PURCHASE_NFT_URL} style={styles.ctaBtn} />
        </View>
        <Image source={{ uri: `${WEBSITE_URL}/assets/images/earth%201.png` }} style={styles.heroImage} resizeMode="contain" />
      </View>

      {/* How we make */}
      <View style={styles.section}>
        <View style={styles.makeRow}>
          <Text style={styles.sectionTitle}>How do we make our Carbon NFT's</Text>
          <Link href="/why-us" asChild>
            <Text style={styles.link}>Learn More</Text>
          </Link>
        </View>
      </View>

      {/* How it works */}
      <View style={[styles.section, styles.sectionAlt]}>
        <Text style={styles.h2}>How it works</Text>
        <Text style={styles.body}>
          Carbon Crowd offers a seamless and transparent way for individuals and businesses to invest in
          projects that drive environmental change. You can select a project that aligns with your
          sustainability goals. Then, invest through our NFT-based system, which represents your share
          in the environmental reductions generated by the project.
        </Text>
        {HOW_IT_WORKS.map((item, i) => (
          <View key={i} style={styles.card}>
            <Image source={{ uri: item.image }} style={styles.cardImage} />
            <Text style={styles.cardText}>{item.text}</Text>
          </View>
        ))}
      </View>

      {/* Why invest */}
      <View style={styles.section}>
        <Text style={styles.h1}>Why invest in Carbon NFTs ?</Text>
        <Image source={{ uri: `${WEBSITE_URL}/assets/images/Rectangle%2077.png` }} style={styles.secureImg} />
        <Text style={styles.h3}>Secure Investment</Text>
        <Text style={styles.body}>
          Investing with Carbon Crowd offers a secure and transparent way to support environmental
          projects that reduce carbon emissions and promote sustainability. Our NFT-based system
          ensures clear ownership of your asset and the environmental reductions achieved by the
          projects you support.
        </Text>
        <Text style={styles.h3}>Flexibility</Text>
        <Text style={styles.body}>
          At Carbon Crowd, we understand that every investor has unique goals. That's why we offer
          flexible buy-in options, so you can choose the level of impact that fits your sustainability
          objectives.
        </Text>
      </View>

      {/* Projects */}
      <View style={[styles.section, styles.sectionAlt]}>
        <View style={styles.row}>
          <Text style={styles.h2}>Projects</Text>
          <Link href="/why-us" asChild>
            <Text style={styles.link}>View all</Text>
          </Link>
        </View>
        {PROJECTS.map((p) => (
          <View key={p.id} style={styles.projectCard}>
            <Image source={{ uri: p.image }} style={styles.projectImage} />
            <Text style={styles.projectTitle}>{p.title}</Text>
            <Text style={styles.body}>{p.description}</Text>
            <Link href="/why-us" asChild>
              <Text style={styles.link}>Learn More</Text>
            </Link>
          </View>
        ))}
      </View>

      {/* Sustainable options */}
      <View style={styles.section}>
        <View style={styles.optionsRow}>
          <Text style={styles.optionLabel}>Sustainable Options For Business</Text>
          <View style={styles.optionImages}>
            <Image source={{ uri: `${WEBSITE_URL}/assets/images/businesssus%201.png` }} style={styles.optionImg} />
            <Image source={{ uri: `${WEBSITE_URL}/assets/images/familysus%201.png` }} style={styles.optionImg} />
          </View>
          <Text style={styles.optionLabel}>Sustainable Options For Individuals</Text>
        </View>
        <View style={styles.optionButtons}>
          <Link href="/calculator-business" asChild>
            <Text style={styles.optionBtn}>For Business</Text>
          </Link>
          <Link href="/calculator-individual" asChild>
            <Text style={styles.optionBtn}>For Individuals</Text>
          </Link>
        </View>
      </View>

      {/* Purchase CTA */}
      <View style={[styles.section, styles.purchaseSection]}>
        <Text style={styles.h1}>Purchase Carbon NFTs</Text>
        <Text style={styles.body}>
          Take the next step in your sustainability journey by investing in environmental projects
          through Carbon Crowd. With secure and transparent purchasing options, you can help support
          impactful initiatives while directly contributing to global emissions reductions.
        </Text>
        <Text style={styles.h4}>Start your investment journey now</Text>
        <PrimaryButton title="Purchase NFT" href={PURCHASE_NFT_URL} />
      </View>

      {/* Blogs */}
      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.h2}>Blogs</Text>
          <Link href="/blog" asChild>
            <Text style={styles.link}>Read all</Text>
          </Link>
        </View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.blogScroll}>
          {BLOGS.slice(0, 6).map((b, i) => (
            <Link key={i} href={{ pathname: '/webview', params: { url: `${WEBSITE_URL}/${b.slug}` } }} asChild>
              <View style={styles.blogCard}>
                <Image source={{ uri: b.image }} style={styles.blogImage} />
                <Text style={styles.blogTitle} numberOfLines={2}>{b.title}</Text>
                <Text style={styles.blogExcerpt} numberOfLines={2}>{b.excerpt}</Text>
              </View>
            </Link>
          ))}
        </ScrollView>
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text style={styles.footerTitle}>Get in touch</Text>
        <Text style={styles.footerText}>Have questions or need assistance? Contact us at:</Text>
        <Text style={styles.footerText}>{CONTACT.address}</Text>
        <Text style={styles.footerLink} onPress={() => Linking.openURL(`mailto:${CONTACT.email}`)}>
          {CONTACT.email}
        </Text>
        <PrimaryButton title="Purchase Carbon NFTs" href={PURCHASE_NFT_URL} style={styles.footerBtn} />
        <Link href="/faq" asChild>
          <Text style={styles.faqLink}>FAQ's</Text>
        </Link>
        <Text style={styles.copyright}>@2025 Carbon Crowd. All rights reserved.</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  content: { paddingBottom: 40 },
  hero: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 24,
    backgroundColor: '#d5efe8',
  },
  heroTextWrap: { marginBottom: 16 },
  heroTitle: { fontSize: 28, fontWeight: '800', color: Brand.link, marginBottom: 8 },
  heroSubtitle: { fontSize: 16, color: '#333', marginBottom: 16 },
  ctaBtn: { alignSelf: 'flex-start' },
  heroImage: { width: '100%', height: 200 },
  section: { padding: 20, paddingVertical: 24 },
  sectionAlt: { backgroundColor: '#f8fcf9' },
  makeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap' },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: Brand.link, flex: 1 },
  link: { fontSize: 16, color: Brand.accent, fontWeight: '600', textDecorationLine: 'underline' },
  h1: { fontSize: 24, fontWeight: '800', color: Brand.link, marginBottom: 12 },
  h2: { fontSize: 20, fontWeight: '700', color: Brand.link, marginBottom: 12 },
  h3: { fontSize: 18, fontWeight: '700', color: Brand.link, marginTop: 16, marginBottom: 8 },
  h4: { fontSize: 16, fontWeight: '700', marginBottom: 12 },
  body: { fontSize: 15, color: '#444', lineHeight: 22, marginBottom: 8 },
  card: { alignItems: 'center', marginBottom: 20 },
  cardImage: { width: 120, height: 120, borderRadius: 60, marginBottom: 12 },
  cardText: { fontSize: 14, color: '#444', textAlign: 'center', lineHeight: 20 },
  secureImg: { width: '100%', height: 180, borderRadius: 8, marginVertical: 12 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  projectCard: { marginBottom: 24, backgroundColor: '#fff', borderRadius: 12, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
  projectImage: { width: '100%', height: 160, borderRadius: 8, marginBottom: 12 },
  projectTitle: { fontSize: 17, fontWeight: '700', color: Brand.link, marginBottom: 8 },
  optionsRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'center', gap: 12 },
  optionLabel: { fontSize: 14, fontWeight: '600', color: Brand.link, flex: 1, minWidth: 120 },
  optionImages: { flexDirection: 'row', gap: 16 },
  optionImg: { width: 80, height: 80 },
  optionButtons: { flexDirection: 'row', justifyContent: 'center', gap: 16, marginTop: 16 },
  optionBtn: { fontSize: 16, color: Brand.primary, fontWeight: '600' },
  purchaseSection: { backgroundColor: '#d5efe8' },
  blogScroll: { marginHorizontal: -20 },
  blogCard: { width: 260, marginRight: 16, backgroundColor: '#fff', borderRadius: 12, padding: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
  blogImage: { width: '100%', height: 140, borderRadius: 8, marginBottom: 8 },
  blogTitle: { fontSize: 14, fontWeight: '700', color: Brand.link, marginBottom: 4 },
  blogExcerpt: { fontSize: 12, color: '#666' },
  footer: { backgroundColor: '#d5efe8', padding: 24, alignItems: 'center' },
  footerTitle: { fontSize: 22, fontWeight: '800', color: Brand.link, marginBottom: 12 },
  footerText: { fontSize: 14, color: '#444', marginBottom: 4, textAlign: 'center' },
  footerLink: { fontSize: 14, color: Brand.accent, marginBottom: 16 },
  footerBtn: { marginBottom: 12 },
  faqLink: { fontSize: 16, color: Brand.accent, fontWeight: '600', marginBottom: 16 },
  copyright: { fontSize: 12, color: '#666' },
});
